from pathlib import Path
import os

### Github URL:
GITHUB_API_URL = "https://api.github.com/repos/Degrado-lab/Ribbon-Tasks/releases"

def load_config(file_path, ribbon_dir):
    """
    Load configuration from config.toml file.
    Creates default config if file doesn't exist.
    
    Returns:
        dict: Configuration dictionary
    """
    try:
        import tomllib  # Python 3.11+
    except ImportError:
        try:
            import tomli as tomllib  # fallback for older Python versions
        except ImportError:
            # If no TOML library available, return defaults
            return get_default_config(ribbon_dir)

    if file_path.exists():
        try:
            with open(file_path, 'rb') as f:
                return tomllib.load(f)
        except Exception as e:
            print(f"Warning: Could not load config file {file_path}: {e}")
            return get_default_config(ribbon_dir)
    else:
        # Create default config file
        config = get_default_config(ribbon_dir)
        create_default_config_file(file_path, config, ribbon_dir)
        return config

def get_default_config(ribbon_dir):
    """Get default configuration values."""
    try:
        tasks_version = get_latest_tasks_version()
    except Exception as e:
        print(f"Error fetching latest tasks version: {e} \n \
               Falling back to default version: v0.1.3")
        tasks_version = "v0.1.3"
    return {
        "tasks_version": tasks_version,
        "tasks_path": str(ribbon_dir / "ribbon_tasks"),
        "containers_path": str(ribbon_dir / "ribbon_containers"),
        "cache_path": str(ribbon_dir / "ribbon_cache"),
    }

def get_latest_tasks_version():
    """Get the latest tasks version from the GitHub repository."""
    import urllib.request
    import json

    api = GITHUB_API_URL+"/latest"
    with urllib.request.urlopen(api, timeout=10) as response:
        data = json.loads(response.read().decode('utf-8'))
        tag = data["tag_name"]
    return tag

def write_config_file(config_file: Path, config: dict):
    """Writes the configuration to the config file."""
    # Write default config
    with open(config_file, 'w') as f:
        f.write(f'# Ribbon Configuration\n')
        f.write(f'# This file is automatically generated but can be edited\n\n')
        for key, value in config.items():
            if isinstance(value, Path):
                value = str(value)
            f.write(f'{key} = "{value}"\n')

def create_default_config_file(config_file, config, ribbon_dir):
    """Create default config.toml file."""
    try:
        # Create the ribbon directory if it doesn't exist
        ribbon_dir.mkdir(parents=True, exist_ok=True)
        
        # Write default config
        write_config_file(config_file, config)
        print(f"Created default config file: {config_file}")
    except Exception as e:
        print(f"Warning: Could not create config file {config_file}: {e}")
