from pathlib import Path
import os

### Main Directory:
# where Task definitions, Containers, and cached Ribbon tasks are stored
# Can be customized by setting RIBBON_HOME environment variable
ribbon_dir = Path(os.environ.get('RIBBON_HOME', '~/.ribbon')).expanduser()

### Ribbon Containers:
DOWNLOAD_DIR = ribbon_dir / "ribbon_containers"

### Ribbon Cached Tasks:
# Here's where we store serialized tasks, to be queued on a cluster
TASK_CACHE_DIR = ribbon_dir / "ribbon_cache"

### Config file:
# All of the below configuration should now be in the config file.
CONFIG_FILE = Path(os.environ.get('RIBBON_CONFIG_FILE', ribbon_dir / "config.toml")).expanduser()

### Github URL:
GITHUB_API_URL = "https://api.github.com/repos/Degrado-lab/Ribbon-Tasks/releases"

### Load configuration from TOML file:
def load_config():
    """
    Load configuration from config.toml file.
    Creates default config if file doesn't exist.
    
    Returns:
        dict: Configuration dictionary
    """
    try:
        import tomllib  # Python 3.11+
    except ImportError:
        try:
            import tomli as tomllib  # fallback for older Python versions
        except ImportError:
            # If no TOML library available, return defaults
            return get_default_config()
    
    if CONFIG_FILE.exists():
        try:
            with open(CONFIG_FILE, 'rb') as f:
                return tomllib.load(f)
        except Exception as e:
            print(f"Warning: Could not load config file {CONFIG_FILE}: {e}")
            return get_default_config()
    else:
        # Create default config file
        config = get_default_config()
        create_default_config_file(config)
        return config

def get_default_config():
    """Get default configuration values."""
    try:
        tasks_version = get_latest_tasks_version()
    except Exception as e:
        print(f"Error fetching latest tasks version: {e} \n \
               Falling back to default version: v0.1.3")
        tasks_version = "v0.1.3"
    return {
        "tasks_version": tasks_version,
        "tasks_path": str(ribbon_dir / "ribbon_tasks"),
    }

def get_latest_tasks_version():
    """Get the latest tasks version from the GitHub repository."""
    import urllib.request
    import json

    api = GITHUB_API_URL+"/latest"
    with urllib.request.urlopen(api, timeout=10) as response:
        data = json.loads(response.read().decode('utf-8'))
        tag = data["tag_name"]
    return tag

def write_config_file(config_file: Path, config: dict):
    """Writes the configuration to the config file."""
    # Write default config
    with open(config_file, 'w') as f:
        f.write(f'# Ribbon Configuration\n')
        f.write(f'# This file is automatically generated but can be edited\n\n')
        f.write(f'tasks_version = "{config["tasks_version"]}"\n')
        f.write(f'tasks_path = "{config["tasks_path"]}"\n')

def create_default_config_file(config):
    """Create default config.toml file."""
    try:
        # Create the ribbon directory if it doesn't exist
        ribbon_dir.mkdir(parents=True, exist_ok=True)
        
        # Write default config
        write_config_file(CONFIG_FILE, config)
        print(f"Created default config file: {CONFIG_FILE}")
    except Exception as e:
        print(f"Warning: Could not create config file {CONFIG_FILE}: {e}")

# Load the configuration
config = load_config()

### Ribbon Task Definitions (from config):
TASKS_VERSION = config["tasks_version"]
TASKS_DIR = Path(config["tasks_path"])

# Set up environment variables for backward compatibility

# The MODULE dir has the actual module
TASKS_MODULE_DIR = TASKS_DIR / TASKS_VERSION / ("Ribbon-Tasks-" + TASKS_VERSION.strip("v")) / "ribbon_tasks"

